
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



public class VelocityGUI extends javax.swing.JFrame {

    private VelocityTabelModel model = new VelocityTabelModel();
    private Measurement mes = new Measurement();
    private File file = new File("src\\data.bin");
    /**
     * Creates new form VelocityGUI
     */
    public VelocityGUI() throws IOException, FileNotFoundException, ClassNotFoundException {
        initComponents();
        jtOut.setModel(model);
        jtOut.setDefaultRenderer(Object.class, new VelocityTableRenderer());
        
        try{
            mes.load(file , model.getVelocities());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Load error!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jmAdd = new javax.swing.JMenuItem();
        jmDelete = new javax.swing.JMenuItem();
        jmMean = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtOut = new javax.swing.JTable();

        jmAdd.setText("Add");
        jmAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAddActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jmAdd);

        jmDelete.setText("Delete");
        jmDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmDeleteActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jmDelete);

        jmMean.setText("Show mean");
        jmMean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMeanActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jmMean);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jScrollPane1.setComponentPopupMenu(jPopupMenu1);

        jtOut.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtOut.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(jtOut);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAddActionPerformed
        VelocityDlg dialog = new VelocityDlg(this, true);
        dialog.setVisible(true);
        if (dialog.isOk()) {
            Velocity a = dialog.getV();
            model.add(a);
        }
    }//GEN-LAST:event_jmAddActionPerformed

    private void jmDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmDeleteActionPerformed
        int[] rows = jtOut.getSelectedRows();
        for(int i = rows.length-1; i >= 0; i--){
            model.delete(rows[i]);
        }
        jtOut.addNotify();
    }//GEN-LAST:event_jmDeleteActionPerformed

    private void jmMeanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMeanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmMeanActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            mes.safe(file, model.getVelocities());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "File error");
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VelocityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VelocityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VelocityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VelocityGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VelocityGUI().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(VelocityGUI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(VelocityGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem jmAdd;
    private javax.swing.JMenuItem jmDelete;
    private javax.swing.JMenuItem jmMean;
    private javax.swing.JTable jtOut;
    // End of variables declaration//GEN-END:variables
}
